### ISSUE TITLE
Producer is hard to maintain from a single main.py

### ISSUE THREAD

**Issue by jgalazm** [lsst-ts/LOVE-producer#49]
It is difficult to identify bottlenecks and bug causes due to the complexity of each one. 
Splitting the producer into 5 (generic (tel+events), commands, scriptqueue, heartbeats,  commands), each managing its own websocket client and served on a separate docker service would allow for easier bug traceability and separation of concerns.

**Comment by jgalazm** [comment]
The initial_state producer won't be needed anymore since it is the effect of an `initial_state` request handled when a message is received on each producer.

**Comment by jgalazm** [comment]
CONFIG_PATH, WS_HOST and WS_PASS should be moved to utils too

**Comment by sebastian-aranda** [comment]
We are no longer using this architecture.
