### ISSUE TITLE
It is not clear which script heartbeat timestamp  should be used

### ISSUE THREAD

**Issue by jgalazm** [lsst-ts/LOVE-producer#53]
Three options:
* `private_rcvStamp`
* `private_sndStamp`
* `datetime.datetime.now().timestamp()`

I tried to implement `private_sndStamp` but it is rendered as "never" in the frontend due to always being a couple seconds in the future compared to Javascript's `new Date()`.

Moving back to `datetime.datetime.now().timestamp()`

**Comment by sebastian-aranda** [comment]
Closed in merge
